collections-config:
  pages:
    path: content/pages
    url: '/[slug]'
    output: true
    _icon: wysiwyg
    _enabled_editors:
      - visual
      - data
  posts:
    path: content/posts
    url: '/blog/[slug]'
    output: true
    _enabled_editors:
      - content
      - data
  staff_members:
    path: content/staff-members
    output: false
    _icon: people
  data:
    path: content/data
    name: Data
    output: false

_inputs:
  large_header: 
    comment: Toggles the size of the top banner.
  show_in_navigation: 
    comment: Toggles a link in the top banner.
  author_staff_member:
    comment: The staff member writing this post.
  testimonials:
    comment: 'Update, add or remove testimonials.'
  phone_extension:
    comment: The digits after dialing the company phone.
  credentials:
    comment: Shown as subtext on staff member summaries.
  contact_email_address:
    comment: Address for the contact form to send to.
  new_window:
    comment: Whether the link opens a new browser tab/window.
  call_to_action:
    type: select
    options:
      values:
        - Contact
        - Blog
  social_icon:
    type: select
    options:
      values:
        - Facebook
        - Instagram
        - LinkedIn
        - Pinterest
        - Tumblr
        - Twitter
        - YouTube
        - RSS
paths:
  collections: content
  data: content/data
  static: static
  uploads: static/uploads
